-- Luxcord database upgrade
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (length(username) between 3 and 32),
  display_name text not null,
  bio text not null default '',
  status text not null default 'Online',
  settings jsonb not null default '{"sound":true,"notifications":true,"enter_send":true,"theme":"dark"}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester uuid not null references public.profiles(id) on delete cascade,
  addressee uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  unique(requester,addressee),
  check(requester <> addressee)
);

alter table public.chat_messages add column if not exists user_id uuid references public.profiles(id) on delete set null;
alter table public.chat_messages add column if not exists reply_to bigint references public.chat_messages(id) on delete set null;

create table if not exists public.message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  unique(message_id,user_id,emoji)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  data jsonb not null default '{}'::jsonb,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.dm_conversations (
  id bigint generated by default as identity primary key,
  user_a uuid not null references public.profiles(id) on delete cascade,
  user_b uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_a,user_b),
  check(user_a < user_b)
);

create table if not exists public.dm_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.dm_conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check(length(message) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.dm_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.dm_messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  unique(message_id,user_id,emoji)
);

create or replace function public.create_notification(target_user uuid, notification_type text, notification_title text, notification_body text, notification_data jsonb default '{}'::jsonb)
returns void language sql security definer set search_path=public as $$
  insert into public.notifications(user_id,type,title,body,data) values(target_user,notification_type,notification_title,notification_body,notification_data);
$$;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.message_reactions enable row level security;
alter table public.notifications enable row level security;
alter table public.dm_conversations enable row level security;
alter table public.dm_messages enable row level security;
alter table public.dm_reactions enable row level security;

create policy "profiles readable" on public.profiles for select to authenticated using (true);
create policy "own profile update" on public.profiles for update to authenticated using (auth.uid()=id) with check(auth.uid()=id);
create policy "own profile insert" on public.profiles for insert to authenticated with check(auth.uid()=id);

create policy "friendships visible to participants" on public.friendships for select to authenticated using (auth.uid()=requester or auth.uid()=addressee);
create policy "send friend requests" on public.friendships for insert to authenticated with check(auth.uid()=requester);
create policy "update received requests" on public.friendships for update to authenticated using (auth.uid()=addressee) with check (auth.uid()=addressee);

create policy "reactions readable" on public.message_reactions for select to authenticated using (true);
create policy "own reactions insert" on public.message_reactions for insert to authenticated with check(auth.uid()=user_id);
create policy "own reactions delete" on public.message_reactions for delete to authenticated using(auth.uid()=user_id);

create policy "own notifications" on public.notifications for select to authenticated using(auth.uid()=user_id);
create policy "own notifications update" on public.notifications for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

create policy "conversation participants read" on public.dm_conversations for select to authenticated using(auth.uid()=user_a or auth.uid()=user_b);
create policy "conversation participants create" on public.dm_conversations for insert to authenticated with check(auth.uid()=user_a or auth.uid()=user_b);

create policy "dm messages participants read" on public.dm_messages for select to authenticated using(exists(select 1 from public.dm_conversations c where c.id=conversation_id and (c.user_a=auth.uid() or c.user_b=auth.uid())));
create policy "dm messages own insert" on public.dm_messages for insert to authenticated with check(auth.uid()=sender_id and exists(select 1 from public.dm_conversations c where c.id=conversation_id and (c.user_a=auth.uid() or c.user_b=auth.uid())));

create policy "dm reactions participants read" on public.dm_reactions for select to authenticated using(exists(select 1 from public.dm_messages m join public.dm_conversations c on c.id=m.conversation_id where m.id=message_id and (c.user_a=auth.uid() or c.user_b=auth.uid())));
create policy "own dm reactions insert" on public.dm_reactions for insert to authenticated with check(auth.uid()=user_id);
create policy "own dm reactions delete" on public.dm_reactions for delete to authenticated using(auth.uid()=user_id);

-- Realtime
alter table public.chat_messages replica identity full;
alter table public.dm_messages replica identity full;
alter table public.notifications replica identity full;
