const SUPABASE_URL="https://mvgqpkdldciwzqgpayoo.supabase.co",
const SUPABASE_KEY="sb_publishable__YusW9lo6b59V8pRXUXIEw_0Ejsw6B4"
.replace(/ /g,""),sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY),$=id=>document.getElementById(id),p=new URLSearchParams(location.search);
let session=null,me=null,room=p.get("room"),reply=null,dm=null,settings={sound:true,notifications:true,enter_send:true,theme:"dark"};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const open=id=>$(id)?.classList.remove("hidden"),close=id=>$(id)?.classList.add("hidden");
async function boot(){let r=await sb.auth.getSession();session=r.data.session;if(session){await loadMe();renderMe();setupRealtime();await Promise.all([loadFriends(),loadDMs(),loadNotifications()])}else renderGuest();bind();if(room)joinRoom(room,p.get("name")||"Guest");else if(!session){$("logout-btn").classList.add("hidden")}}
async function loadMe(){let r=await sb.from("profiles").select("*").eq("id",session.user.id).maybeSingle();if(r.data)me=r.data;else{let n=(session.user.user_metadata?.username||session.user.email.split("@")[0]).replace(/[^a-zA-Z0-9_.-]/g,"").slice(0,32)||"user";r=await sb.from("profiles").insert({id:session.user.id,username:n,display_name:n}).select().single();me=r.data}settings={...settings,...(me?.settings||{})};document.body.dataset.theme=settings.theme}
function renderMe(){let n=me?.display_name||me?.username||"User";$("me-name").textContent=n;$("me-status").textContent=me?.status||"Online";$("me-avatar").textContent=n[0].toUpperCase()}
function renderGuest(){let n=p.get("name")||"Guest";$("me-name").textContent=n;$("me-status").textContent="Guest";$("me-avatar").textContent=n[0].toUpperCase();$("settings-btn").classList.add("hidden");$("profile-btn").classList.add("hidden")}
function bind(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$("logout-btn").onclick=async()=>{await sb.auth.signOut();location.href="index.html"};$("settings-btn").onclick=openSettings;$("profile-btn").onclick=openProfile;document.querySelectorAll(".modal-close").forEach(b=>b.onclick=()=>close(b.closest(".modal").id));$("notification-btn").onclick=()=>{open("notification-panel");loadNotifications()};$("clear-notifications").onclick=clearNotifications;$("new-room").onclick=createRoom;$("home-room").onclick=createRoom;$("home-friends").onclick=()=>view("friends");$("home-dms").onclick=()=>view("dms");$("leave-btn").onclick=leaveRoom;$("send-btn").onclick=sendRoom;$("message-input").oninput=e=>$("char-counter").textContent=e.target.value.length+"/1000";$("message-input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey&&settings.enter_send){e.preventDefault();sendRoom()}};$("cancel-reply").onclick=()=>{reply=null;close("reply-bar")};$("search-users").onclick=searchUsers;$("user-search").onkeydown=e=>{if(e.key==="Enter")searchUsers()};$("refresh-friends").onclick=loadFriends;$("save-profile").onclick=saveProfile;$("save-settings").onclick=saveSettings;$("dm-send").onclick=sendDM;$("dm-input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey&&settings.enter_send){e.preventDefault();sendDM()}}}
function view(v){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(v+"-view").classList.remove("hidden");document.querySelectorAll(".rail-btn[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$("view-title").textContent={home:"Home",friends:"Friends",dms:"Direct Messages",room:"Room Chat"}[v];if(v==="friends")loadFriends();if(v==="dms")loadDMs()}
async function createRoom(){let r=prompt("Room code");if(r?.trim())joinRoom(r.trim(),me?.username||p.get("name")||"Guest")}
async function joinRoom(r,n){room=r;$("room-display").textContent=r;$("room-name-side").textContent=r;$("room-subtitle").textContent="• "+r;view("room");if(session&&me)await sb.from("user_status").upsert({room:r,name:me.username,last_active:Date.now(),is_typing:false,typing_timestamp:Date.now()},{onConflict:"room,name"});await refreshRoom()}
async function refreshRoom(){if(!room)return;let q=await sb.from("chat_messages").select("*").eq("room",room).order("id");if(q.error){$("chat-display").innerHTML='<div class="empty-state"><h2>Database setup needed</h2><p>Run supabase/schema.sql in Supabase SQL Editor.</p></div>';return}let ms=q.data||[],rx=[];if(session&&ms.length){let x=await sb.from("message_reactions").select("*").in("message_id",ms.map(m=>m.id));rx=x.data||[]}$("chat-display").innerHTML=ms.map(m=>{let rr=ms.find(x=>String(x.id)===String(m.reply_to)),acts=session?`<button onclick="reactRoom(${m.id},'❤️')">❤️</button><button onclick="reactRoom(${m.id},'👍')">👍</button><button onclick="reactRoom(${m.id},'😂')">😂</button>`:"";return `<article class="message"><div class="message-avatar">${esc((m.name||"?")[0])}</div><div class="message-body"><div class="message-head"><b>${esc(m.name)}</b><time>${new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div>${rr?`<div class="reply-preview">Replying to ${esc(rr.name)}: ${esc(String(rr.message).slice(0,100))}</div>`:""}<div class="message-text">${esc(m.message)}</div><div class="message-actions"><button onclick="replyRoom(${m.id})">↩ Reply</button>${acts}</div><div class="reactions">${groups(rx.filter(x=>x.message_id===m.id))}</div></div></article>`}).join("");$("chat-display").scrollTop=$("chat-display").scrollHeight}
function groups(rs){let a={};rs.forEach(r=>a[r.emoji]=(a[r.emoji]||0)+1);return Object.entries(a).map(([e,n])=>`<span class="reaction">${esc(e)} ${n}</span>`).join("")}
window.replyRoom=async id=>{let r=await sb.from("chat_messages").select("*").eq("id",id).single();reply=r.data;$("reply-text").textContent=`Replying to ${reply.name}: ${String(reply.message).slice(0,100)}`;open("reply-bar");$("message-input").focus()}
window.reactRoom=async(id,e)=>{let r=await sb.from("message_reactions").select("id").eq("message_id",id).eq("user_id",session.user.id).eq("emoji",e).maybeSingle();if(r.data)await sb.from("message_reactions").delete().eq("id",r.data.id);else await sb.from("message_reactions").insert({message_id:id,user_id:session.user.id,emoji:e});refreshRoom()}
async function sendRoom(){let input=$("message-input"),t=input.value.trim();if(!t||!room)return;let r=await sb.from("chat_messages").insert({room,name:me?.username||p.get("name")||"Guest",message:t,user_id:session?.user?.id||null,reply_to:reply?.id||null});if(r.error)return alert(r.error.message);input.value="";$("char-counter").textContent="0/1000";reply=null;close("reply-bar");refreshRoom()}
async function leaveRoom(){if(session&&room&&me)await sb.from("user_status").delete().eq("room",room).eq("name",me.username);room=null;view("home")}
async function loadMembers(){let r=await sb.from("user_status").select("*").eq("room",room);$("room-members").innerHTML=(r.data||[]).filter(x=>Date.now()-x.last_active<30000).map(x=>`<div class="side-item">🟢 ${esc(x.name)}</div>`).join("")}
async function loadFriends(){if(!session)return;let r=await sb.from("friendships").select("*").or(`requester.eq.${session.user.id},addressee.eq.${session.user.id}`),fs=r.data||[],ids=[...new Set(fs.flatMap(x=>[x.requester,x.addressee]).filter(x=>x!==session.user.id))],ps=[];if(ids.length){let q=await sb.from("profiles").select("id,username,display_name,status").in("id",ids);ps=q.data||[]}let map=Object.fromEntries(ps.map(x=>[x.id,x])),inc=fs.filter(x=>x.addressee===session.user.id&&x.status==="pending"),friends=fs.filter(x=>x.status==="accepted");$("requests-list").innerHTML=inc.map(x=>person(map[x.requester],`<button class="primary" onclick="acceptFriend('${x.id}')">Accept</button><button class="secondary" onclick="declineFriend('${x.id}')">Decline</button>`)).join("")||'<div class="muted">No pending requests.</div>';$("friends-list").innerHTML=friends.map(x=>{let id=x.requester===session.user.id?x.addressee:x.requester;return person(map[id],`<button class="secondary" onclick="openDM('${id}')">Message</button>`)}).join("")||'<div class="muted">No friends yet.</div>';$("friend-summary").textContent=friends.length+" friend"+(friends.length===1?"":"s");}
function person(p,a){return p?`<div class="person-card"><div class="avatar">${esc((p.display_name||p.username)[0])}</div><div class="info"><b>${esc(p.display_name||p.username)}</b><small>@${esc(p.username)} • ${esc(p.status||"Online")}</small></div><div class="actions">${a}</div></div>`:""}
async function searchUsers(){if(!session)return;let q=$("user-search").value.trim();if(q.length<2)return;let r=await sb.from("profiles").select("id,username,display_name,status").ilike("username","%"+q+"%").neq("id",session.user.id).limit(20);$("friend-results").innerHTML=(r.data||[]).map(x=>person(x,`<button class="primary" onclick="sendFriend('${x.id}')">Add friend</button>`)).join("")||'<div class="muted">No users found.</div>'}
window.sendFriend=async id=>{let e=await sb.from("friendships").select("id").or(`and(requester.eq.${session.user.id},addressee.eq.${id}),and(requester.eq.${id},addressee.eq.${session.user.id})`);if(e.data?.length)return alert("Friend request already exists.");let r=await sb.from("friendships").insert({requester:session.user.id,addressee:id});if(r.error)return alert(r.error.message);await notify(id,"friend_request","New friend request",`${me.username} sent you a friend request.`);loadFriends()}
window.acceptFriend=async id=>{let r=await sb.from("friendships").update({status:"accepted"}).eq("id",id).eq("addressee",session.user.id).select().single();if(r.data)await notify(r.data.requester,"friend_accept","Friend request accepted",`${me.username} accepted your request.`);loadFriends();loadDMs()}
window.declineFriend=async id=>{await sb.from("friendships").update({status:"declined"}).eq("id",id).eq("addressee",session.user.id);loadFriends()}
async function notify(id,type,title,body){await sb.rpc("create_notification",{target_user:id,notification_type:type,notification_title:title,notification_body:body,notification_data:{}})}
async function loadNotifications(){if(!session)return;let r=await sb.from("notifications").select("*").eq("user_id",session.user.id).order("created_at",{ascending:false}).limit(30),ns=r.data||[];$("notification-count").textContent=ns.filter(x=>!x.read).length;$("notification-count").classList.toggle("hidden",!ns.some(x=>!x.read));$("notifications-list").innerHTML=ns.map(n=>`<div class="notification ${n.read?"":"unread"}" onclick="readNotification('${n.id}')"><b>${esc(n.title)}</b><div>${esc(n.body)}</div><small>${new Date(n.created_at).toLocaleString()}</small></div>`).join("")||'<div class="muted" style="padding:15px">No notifications.</div>'}
window.readNotification=async id=>{await sb.from("notifications").update({read:true}).eq("id",id);loadNotifications()};async function clearNotifications(){await sb.from("notifications").update({read:true}).eq("user_id",session.user.id);loadNotifications()}
async function loadDMs(){if(!session)return;let r=await sb.from("friendships").select("*").or(`requester.eq.${session.user.id},addressee.eq.${session.user.id}`).eq("status","accepted"),ids=(r.data||[]).map(x=>x.requester===session.user.id?x.addressee:x.requester),ps=[];if(ids.length){let q=await sb.from("profiles").select("id,username,display_name").in("id",ids);ps=q.data||[]}$("dm-people").innerHTML=ps.map(x=>`<div class="side-item" onclick="openDM('${x.id}')"><div class="avatar">${esc((x.display_name||x.username)[0])}</div>${esc(x.display_name||x.username)}</div>`).join("")||'<div class="muted" style="padding:10px">Add friends to start DMs.</div>'}
window.openDM=async id=>{let a=[session.user.id,id].sort(),r=await sb.from("dm_conversations").select("*").eq("user_a",a[0]).eq("user_b",a[1]).maybeSingle();if(!r.data)r=await sb.from("dm_conversations").insert({user_a:a[0],user_b:a[1]}).select().single();if(r.error)return alert(r.error.message);dm=r.data;view("dms");open("dm-messages");open("dm-composer");close("dm-empty");refreshDM()}
async function refreshDM(){if(!dm)return;let r=await sb.from("dm_messages").select("*").eq("conversation_id",dm.id).order("created_at"),ms=r.data||[],ids=[...new Set(ms.map(x=>x.sender_id))],ps=[];if(ids.length){let q=await sb.from("profiles").select("id,username,display_name").in("id",ids);ps=q.data||[]}let map=Object.fromEntries(ps.map(x=>[x.id,x]));$("dm-messages").innerHTML=ms.map(m=>{let u=map[m.sender_id]||{};return `<article class="message"><div class="message-avatar">${esc((u.display_name||u.username||"?")[0])}</div><div class="message-body"><div class="message-head"><b>${esc(u.display_name||u.username||"User")}</b><time>${new Date(m.created_at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</time></div><div class="message-text">${esc(m.message)}</div><div class="message-actions"><button onclick="reactDM(${m.id},'❤️')">❤️</button><button onclick="reactDM(${m.id},'👍')">👍</button></div></div></article>`}).join("");$("dm-messages").scrollTop=$("dm-messages").scrollHeight}
async function sendDM(){let t=$("dm-input").value.trim();if(!t||!dm)return;let r=await sb.from("dm_messages").insert({conversation_id:dm.id,sender_id:session.user.id,message:t});if(r.error)return alert(r.error.message);$("dm-input").value="";let target=dm.user_a===session.user.id?dm.user_b:dm.user_a;await notify(target,"dm","New direct message",`${me.display_name||me.username} sent you a message.`);refreshDM()}
window.reactDM=async(id,e)=>{let r=await sb.from("dm_reactions").select("id").eq("message_id",id).eq("user_id",session.user.id).eq("emoji",e).maybeSingle();if(r.data)await sb.from("dm_reactions").delete().eq("id",r.data.id);else await sb.from("dm_reactions").insert({message_id:id,user_id:session.user.id,emoji:e});refreshDM()}
function openProfile(){if(!session)return alert("Create an account to use profiles.");$("profile-username").value=me.username||"";$("profile-display-name").value=me.display_name||"";$("profile-status").value=me.status||"Online";$("profile-bio").value=me.bio||"";open("profile-modal")}
async function saveProfile(){let u=$("profile-username").value.trim().replace(/[^a-zA-Z0-9_.-]/g,"");if(u.length<3)return $("profile-error").textContent="Username must be at least 3 characters.";let r=await sb.from("profiles").update({username:u,display_name:$("profile-display-name").value.trim()||u,status:$("profile-status").value.trim()||"Online",bio:$("profile-bio").value.trim()}).eq("id",session.user.id).select().single();if(r.error)return $("profile-error").textContent=r.error.message;me=r.data;renderMe();close("profile-modal")}
function openSettings(){$("setting-sound").checked=!!settings.sound;$("setting-notify").checked=!!settings.notifications;$("setting-enter").checked=!!settings.enter_send;$("setting-theme").value=settings.theme||"dark";open("settings-modal")}
async function saveSettings(){settings={sound:$("setting-sound").checked,notifications:$("setting-notify").checked,enter_send:$("setting-enter").checked,theme:$("setting-theme").value};if(session)await sb.from("profiles").update({settings}).eq("id",session.user.id);document.body.dataset.theme=settings.theme;close("settings-modal");if(settings.notifications&&"Notification"in window&&Notification.permission==="default")Notification.requestPermission()}
function setupRealtime(){sb.channel("luxcord-live").on("postgres_changes",{event:"*",schema:"public",table:"chat_messages"},x=>{if(room&&x.new?.room===room)refreshRoom()}).on("postgres_changes",{event:"*",schema:"public",table:"dm_messages"},x=>{if(dm&&x.new?.conversation_id===dm.id)refreshDM()}).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:`user_id=eq.${session.user.id}`},loadNotifications).subscribe()}
setInterval(()=>{if(room)loadMembers()},4000);boot();
